CREATE TABLE RSAEntity (
    id INT IDENTITY(1,1) PRIMARY KEY,
    username NVARCHAR(255) NOT NULL,
    name NVARCHAR(255) NOT NULL,
    pub NVARCHAR(MAX) NOT NULL,
    signature NVARCHAR(MAX) NOT NULL,
    data NVARCHAR(MAX) NOT NULL
);
